version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./database-data/mongodb:/data/db:rw
